config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'welcome/index'
  get '/users/:id', to: 'users#get_user', as: :get_user
  get '/user/my_article', to: 'users#show', as: :show

  resources :user_articles
  resources :articles 
  resources :users
  resources :comments
  
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5 }
  belongs_to :user,  optional: true
  has_many :user_articles, dependent: :destroy
  has_many :favorite_articles, through: :user_articles, source: :user
  has_many :comments, as: :commentable 
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :commenter, :body, presence: true
  belongs_to :commentable, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :articles
  has_many :user_articles, dependent: :destroy
  has_many :favorite_articles, through: :user_articles, source: :article
  has_many :comments, as: :commentable

  enum role: [:user, :author]

end

app/models/user_article.rb
class UserArticle < ApplicationRecord
  validates_uniqueness_of :article_id, :scope => :user_id
  belongs_to :user
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    root_path
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

  protected 
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @articles = Article.all
  end
  
  def show
    @article = Article.find(params[:id])
    authorize @article
  end

  def new
    @article = Article.new
    authorize @article
  end
  
  def edit
    @article ||= Article.find(params[:id])
    authorize @article
  end
  
  def create
    @article = articles_for_user.new(article_params)
    authorize @article
    if @article.save
      redirect_to article_path(@article.id)
    else
      render 'new'
    end
  end

  def update
    authorize set_article
    if set_article.update(article_params)
      redirect_to set_article
    else
      render 'edit'
    end
  end

  def destroy
    authorize set_article
    set_article.destroy
  
    redirect_to show_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end

  def set_article
    @article ||= articles_for_user.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def destroy
    comment = Comment.find(params[:id])
    authorize comment
    comment.destroy
    redirect_to send("#{comment.commentable.class.to_s.downcase}_path", comment.commentable)
  end
  
  def create
    comment = Comment.new(comment_params)
    authorize comment
    if comment.save
      flash[:notice] = "Saved"
      redirect_to send("#{comment.commentable.class.to_s.downcase}_path", comment.commentable)
    else
      flash[:notice] = "Don't save"
      redirect_to send("#{comment.commentable.class.to_s.downcase}_path", comment.commentable)
    end
  end

  private
  
  def comment_params
    params.require(:comment).permit(:commenter, :body, :commentable_id, :commentable_type)
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
    @users = User.all
  end
  def show
    @articles = current_user.articles    
  end
end

app/controllers/user_articles_controller.rb
class UserArticlesController < ApplicationController
  def index
    @saved_aritcles = current_user.favorite_articles
  end

  def create
    @favorite_article = current_user.user_articles.new(article_id: find_article.id)
    authorize @favorite_article
    if @favorite_article.save
      redirect_to articles_path
      flash[:alert] = "Saved"
    else
      redirect_to articles_path
      flash[:alert] = "Don't saved"
    end
  end

  def destroy
    authorize current_user
    current_user.favorite_articles.delete(find_article)
    redirect_to user_articles_path
  end

  private

  def parametrs
    params.permit(:id)
  end

  def find_article
    @article ||= Article.find(parametrs[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = current_user
    @articles = @user.articles
    authorize current_user
  end

  def get_user
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @articles = Article.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def articles_for_user
    current_user.articles
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/user_articles_helper.rb
module UserArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= form_with model: @article, url: article_path(@article.id), local: true do |form| %>
<% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>


<%= link_to 'Back', user_path(current_user.id) %>
<br>
<%= link_to 'Home', root_path%>

app/views/articles/index.html.erb
<h1>All Articles from all users</h1>
<div style="margin: 20px;">
  <%= link_to 'Home',root_path, :class => "btn btn-light" %>
</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Text</th>
      <th scope="col">Id</th>
      <th scope="col">Email</th>
      <th scope="col">Comments</th>
      <th scope="col">Show</th>
      <% if user_signed_in? %>
        <th scope="col">Save</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% @articles.includes(:user).each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td><%= article.id %></td>
        <td><%= article.user.email %></td>
        <td><%= article.comments.count %></td>
        <td><%= link_to 'Show', article_path(article.id), :class => "btn btn-light" %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Save', user_articles_path(id: article.id), method: :create, :class => "btn btn-light" %></td>
        <%end%>
      </tr>
    <% end %>
    </tr>
  </tbody>
</table>

app/views/articles/new.html.erb
<h1>New article</h1>
<%= form_with model: @article, url: articles_path, :html => {:class => "form-horizontal center"}, local: true do |form| %>
<% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <div class="form-group">
      <%= form.label :title, class: "col-md-4 control-label" %><br>
      <div class="col-md-8">
        <%= form.text_field :title %>
      </div>
    </div>
  </p>
  <p>
    <div class="form-group">
      <%= form.label :text, class: "col-md-4 control-label" %><br>
      <div class="col-md-8">
        <%= form.text_area :text, class: "col-md-4 control-label" %>
      </div>
    </div>
  </p>
  <p>
    <%= form.submit class: 'btn btn-primary'%>
  </p>
<% end %>

<%= link_to 'Back', show_path(current_user.id) %> |
<%= link_to 'Home', root_path %>

app/views/articles/show.html.erb
<p style="font-size: 30px;">
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p style="font-size: 30px;">
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>


<%= link_to 'Back', articles_path %>
<% if user_signed_in? && current_user == @article.user %>
| <%= link_to 'Edit', edit_article_path(@article.id) %> 
<%end%>
| <%= link_to 'Home', root_path%>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
  <% if comment.commenter == @article.user.email %>
    | <b>Owner</b>
  <%end%>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
<% if @current_user.email == @article.user.email || comment.commenter == @current_user.email  %>
  <%= link_to 'Destroy Comment', comment_path(comment.id),
               method: :delete,
               data: { confirm: 'Are you sure?' }, class: 'btn btn-light' %>
  <br>
  ---------------------
<%end%>
<br>
</p>

app/views/comments/_form.html.erb
<%= form_with model: @article.comments.build, local: true do |form| %>
  <p>
    <%= form.hidden_field :commenter, :value => current_user.email %>
    <%= form.hidden_field :commentable_id, value: @article.id %>
    <%= form.hidden_field :commentable_type, value: "Article" %>
    
  </p>
  <p>
    <%= form.label :Comment %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit class: 'btn btn-primary' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudyApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= yield %>
  </ class="container">

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

</html>

app/views/persons/profile.html.erb
<h1>Profiles</h1>

<% @users.each_with_index do |user, index| %>
    <tr>
      <%= index + 1 %>
      <%= ' -- '%>
      <td><%= user.email %></td>
      <br>
    </tr>
<% end %>
<%= link_to 'Home', root_path%>

app/views/user_articles/index.html.erb
<h1>Saved Articles</h1>
<div style="margin: 20px;">
  <%= link_to 'Home', root_path, :class => "btn btn-light" %>
</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Text</th>
      <th scope="col">Id</th>
      <th scope="col">Email</th>
      <th scope="col">Show</th>
      <th scope="col">Remove</th>
    </tr>
  </thead>
  <tbody>
    <tr>
       <% @saved_aritcles.includes(:user).each do |article| %>
        <tr>
          <td><%= article.title %></td>
          <td><%= article.text %></td>
          <td><%= article.id %></td>
          <td><%= article.user.email %></td>
          <td><%= link_to 'Show', article_path(article.id), :class => "btn btn-light"  %></td>
          <td><%= link_to 'Remove', user_article_path(id: article.id), 
                method: :delete, 
                data: { confirm: 'Are you sure?' }, :class => "btn btn-light"  %></td>
        </tr>
      <% end %>
    </tr>
  </tbody>
</table>

app/views/users/get_user.erb
<p style="font-size: 30px;">
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p style="font-size: 30px;">
  <strong>Id:</strong>
  <%= @user.id %>
</p>
<h2>Comments:</h2>
<div style="margin-left: 20px;"> 
  <% @user.comments.each do |c| %>
  <div>
    <h5>Comment by  <%= c.commenter %></h5>
    <%= c.body %>
    </div>
  <br>
<% end %>
</div>

<p>


<%=  form_with model: @user.comments.build,  local: true  do |form| %>
  <p>
    <%= form.hidden_field :commenter, :value => current_user.email %>
    <%= form.hidden_field :commentable_id, value: @user.id %>
    <%= form.hidden_field :commentable_type, value: "User" %>
  </p>
  <p>
    <%= form.label :Comment %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit class: 'btn btn-primary' %>
  </p>
<% end %>

<%= link_to 'Back', users_path %>
| <%= link_to 'Home', root_path%>

app/views/users/index.html.erb
<h1>Profiles</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Email</th>
      <th scope="col">id</th>
      <% if user_signed_in?%>
        <th scope="col">Show</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <tr>
    <% @users.each_with_index do |user, index| %>
        <td><%= index + 1 %></td>
        <td><%= user.email %></td>
        <td><%= user.id %></td>
        <% if user_signed_in?%>
          <td><%= link_to 'Show', get_user_path(user.id), class: "btn btn-light" %></td>
        <% end %>
      </tr>
      <% end %>
  </tbody>
</table>

<%= link_to 'Home', root_path, :class => "btn btn-light" %>

app/views/users/show.html.erb
<h1><%= "Articles by #{@user.email}" %></h1>
<div style="margin: 20px;">
  <% if user_signed_in? %>
    <%= link_to 'New article', new_article_path, :class => "btn btn-light" %>
  <% else %>
    fuck off
  <% end %>
  <%= link_to 'Home', root_path, :class => "btn btn-light" %>
</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Title</th>
      <th scope="col">Text</th>
      <th scope="col">Show</th>
      <th scope="col">Edit</th>
      <th scope="col">Destroy</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% @articles.each do |article| %>
        <tr>
          <td><%= article.id %></td>
          <td><%= article.title %></td>
          <td><%= article.text %></td>
          <% if article.user == current_user %>
            <td><%= link_to 'Show', article_path(article.id) %></td>
            <td><%= link_to 'Edit', edit_article_path(article.id) %></td>
            <td><%= link_to 'Destroy', article_path(article.id),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tr>
  </tbody>
</table>

app/views/welcome/index.html.erb
<h1>Hey, Rails</h1>
<% if user_signed_in?%>
		<%= link_to "Saved articles - #{current_user.favorite_articles.count}", user_articles_path, :class => "btn btn-primary"  %> 
	<% if user_signed_in? && current_user.author?%>
		<%= link_to "My articles - #{current_user.articles.count}", show_path,:class => "btn btn-primary"  %> 
	<% end %>
<% end %>
<%= link_to "All articles - #{@articles.count}", articles_path, :class => "btn btn-primary" %>  
<br>
<br>
<% if user_signed_in? %>
	<span>Hey, my friend - <%= current_user.email %></span>
	<br>
	<%= link_to "Log out", destroy_user_session_path, :method => :delete %>
<% else %>
	<%= link_to "Sign in", new_user_session_path %> or <%= link_to 'Sign up', new_user_registration_path %>
<% end %>
<br>
<br>

<%= link_to "Users", users_path %>